name: PHP CI with MySQL

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  php-mysql-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gestion_ecole
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mysqli, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist || true

      - name: Setup .env file
        run: |
          echo "DB_CONNECTION=mysql" > .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=gestion_ecole" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Run PHP tests
        run: |
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit
          else
            echo "Aucun test à exécuter pour l’instant."
          fi
